name: Bar Chart Render
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install puppeteer
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run Render
        run: node render.js

      - name: Simpan Video
        uses: actions/upload-artifact@v4
        with:
          name: hasil-video
          path: video_output.mp4
